export const enum FLASH_STEP {
    REQUEST_PORT = 'REQUEST_PORT',
    MANIFEST_PATH = 'MANIFEST_PATH',
    FLASH_FIRMWARE = 'FLASH_FIRMWARE',
}

export const enum FLASH_STATUS {
    NONE = 'NONE',
    SUCCESS = 'SUCCESS',
    FAILED = 'FAILED',
    UNKNOWN = 'UNKNOWN',
    ABORTED = 'ABORTED',
}

export enum MODAL_TYPE {
    SELECT_BOARD = 'SELECT_BOARD',
    DEVTOOLS = 'DEVTOOLS',
    SELECT_PORT = 'SELECT_PORT',
    BEFORE_SELECT_BOARD = 'BEFORE_SELECT_BOARD',
    UPDATE_NETWORK = 'UPDATE_NETWORK',
    BEFORE_FLASHING = 'BEFORE_FLASHING',
    AP_MODE = 'AP_MODE',
    NONE = 'NONE',
}

export enum ACTION {
    NEXT = 'NEXT',
    PREV = 'PREV',
}

export enum STEP_ACTION {
    CHANGE_DEVICE_MODE = 'CHANGE_DEVICE_MODE',
    INSTALL_OPENIRIS = 'INSTALL_OPENIRIS',
    SELECT_NETWORK = 'SELECT_NETWORK',
    UPDATE_NETWORK = 'UPDATE_NETWORK',
    SELECT_MODE = 'SELECT_MODE',
}

export enum INIT_WIZARD_STEPS {
    PROCESS_INIT = 'PROCESS_INIT',
    SELECT_PROCESS = 'SELECT_PROCESS',
    SELECT_BOARD = 'SELECT_BOARD',
}

export enum FLASH_WIZARD_STEPS {
    FLASH_PROCESS_SUCCESS = 'FLASH_PROCESS_SUCCESS',
    FLASH_PROCESS_FAILED = 'FLASH_PROCESS_FAILED',
    FLASH_PROCESS = 'FLASH_PROCESS',
}

export enum FLASH_MODE {
    TERMINAL = 'TERMINAL',
    WIRELESS = 'WIRELESS',
    WIRED = 'WIRED',
}

export enum TERMINAL_WIZARD_STEPS {
    TERMINAL_BEFORE_PROCEEDING = 'TERMINAL_BEFORE_PROCEEDING',
}

export enum DEVICE_MODE_WIZARD {
    DEVICE_SWITCHING_DEVICE_MODE_SUCCESS = 'DEVICE_SWITCHING_DEVICE_MODE_SUCCESS',
    DEVICE_SWITCHING_DEVICE_MODE_PROCESS = 'DEVICE_SWITCHING_DEVICE_MODE_PROCESS',
    DEVICE_SWITCHING_DEVICE_MODE_FAILED = 'DEVICE_SWITCHING_DEVICE_MODE_FAILED',
    DEVICE_SWITCHING_DEVICE_MODE = 'DEVICE_SWITCHING_DEVICE_MODE',
    DETECT_DEVICE_MODE_FAILED = 'DETECT_DEVICE_MODE_FAILED',
    DEVICE_SELECT_DEVICE_MODE = 'DEVICE_SELECT_DEVICE_MODE',
    DEVICE_BEFORE_PROCEEDING = 'DEVICE_BEFORE_PROCEEDING',
    DETECT_DEVICE_MODE = 'DETECT_DEVICE_MODE',
}

export enum SELECT_PORT_WIZARD {
    SELECT_CHECK_PORT_CONNECTION = 'SELECT_CHECK_PORT_CONNECTION',
    SELECT_PORT_BEFORE_PROCEEDING = 'PORT_BEFORE_PROCEEDING',
    SELECT_PORT = 'SELECT_PORT',
}

export enum SELECT_MODE_WIZARD {
    SELECT_MODE = 'SELECT_MODE',
}
export enum UPDATE_NETWORK_WIZARD {
    UPDATE_NETWORK_VERYFICATION_FAILED = 'UPDATE_NETWORK_VERYFICATION_FAILED',
    UPDATE_NETWORK_INVALID_MODE = 'UPDATE_NETWORK_INVALID_MODE',
    UPDATE_NETWORK_CHECK_MODE = 'UPDATE_NETWORK_CHECK_MODE',
    UPDATE_SWITCHING_MODE = 'UPDATE_SWITCHING_MODE',
}

export enum WIRED_WIZARD_STEPS {
    WIRED_SETUP_TRACKER_PROCESS_SUCCESS = 'WIRED_SETUP_TRACKER_PROCESS_SUCCESS',
    WIRED_SETUP_TRACKER_PROCESS_FAILED = 'WIRED_SETUP_TRACKER_PROCESS_FAILED',
    WIRED_SETUP_TRACKER_PROCESS = 'WIRED_SETUP_TRACKER_PROCESS',
    WIRED_SETUP_TRACKER_NAME = 'WIRED_SETUP_TRACKER_NAME',
}

export enum WIRELESS_WIZARD_STEPS {
    WIRELESS_WIFI_CONNECTING_PROCESS_SUCCESS = 'WIRELESS_WIFI_CONNECTING_PROCESS_SUCCESS',
    WIRELESS_WIFI_CONNECTING_PROCESS_FAILED = 'WIRELESS_WIFI_CONNECTING_PROCESS_FAILED',
    WIRELESS_PORT_CONNECTION_VALIDATION = 'WIRELESS_PORT_CONNECTION_VALIDATION',
    WIRELESS_VALIDATE_PORT_CONNECTION = 'WIRELESS_VALIDATE_PORT_CONNECTION',
    WIRELESS_SCAN_FOR_NETWORKS_FAILED = 'WIRELESS_SCAN_FOR_NETWORKS_FAILED',
    WIRELESS_WIFI_CONNECTING_PROCESS = 'WIRELESS_WIFI_CONNECTING_PROCESS',
    WIRELESS_SETUP_WIRELESS_MODE = 'WIRELESS_SETUP_WIRELESS_MODE',
    WIRELESS_SCAN_FOR_NETWORKS = 'WIRELESS_SCAN_FOR_NETWORKS',
    WIRELESS_SETUP_CREDENTIALS = 'WIRELESS_SETUP_CREDENTIALS',
    WIRELESS_SELECT_NETWORK = 'WIRELESS_SELECT_NETWORK',
    WIRELESS_MANUAL_SETUP = 'WIRELESS_MANUAL_SETUP',
    WIRELESS_SETUP_MDNS = 'WIRELESS_SETUP_MDNS',
}
