export enum CONNECTION_STATUS {
    CONNECTED = 'CONNECTED',
    DISCONNECTED = 'DISCONNECTED',
    DISCONNECTING = 'DISCONNECTING',
    CONNECTING = 'CONNECTING',
    INACTIVE = 'INACTIVE',
    FAILED = 'FAILED',
}
export enum CAMERA_STREAM_TYPE {
    RAW = 'camera',
    ALGORITHM = 'algorithm',
}
